### ISSUE TITLE
Vue Nested SFC does not work with Stackblitz

### ISSUE THREAD

**Issue by louiss0** [HunYan-io/vite-plugin-vue-nested-sfc#1]
I don't know why but Vue this extension does not work on stackblitz. I don't know why but it seems to only work in VSCode. This is strange. I didn't realize I had to use vue compiler options but I did afterwards but things did not work. 

```
ENOENT: no such file or directory, open 'home/projects/vitejs-vite-rfm3xc/src/components/HelloWorld.vue'
```
 
https://stackblitz.com/edit/vitejs-vite-rfm3xc?file=src/components/HelloWorld.vue

This is my package json. 
```
 "dependencies": {
    "vite-plugin-vue-nested-sfc": "^0.0.4",
    "vue": "^3.2.47"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.1.0",
    "typescript": "^5.0.2",
    "vite": "^4.3.2",
    "vue-tsc": "^1.4.2"
  }
```

**Comment by hunyan-io** [comment]
Fixed on `v0.0.5`
