### ISSUE TITLE
Lang is vue removes Syntax Highlighting

### ISSUE THREAD

**Issue by louiss0** [HunYan-io/vite-plugin-vue-nested-sfc#7]
**Vue version:** 3.3.0
**Volar version:** 1.6.0
**Vue Nested SFC Version:** 0.1.1  

**I remember seeing in a recent version that you have decided to support `lang="vue"`. But it does not work.**
 
This is what my editor looks like **The white indicates there is no syntax highlighting** 
![Screenshot 2023-05-11 205830](https://github.com/HunYan-io/vite-plugin-vue-nested-sfc/assets/29028601/6b82f497-d48c-42c3-8b72-b9328546dea5)

**It was fine when the last two versions came out**
![Screenshot 2023-05-08 133236](https://github.com/HunYan-io/vite-plugin-vue-nested-sfc/assets/29028601/934bcfb0-8755-4618-b25f-1161cd584ee7)

**Comment by hunyan-io** [comment]
It's Volar extension that supported `lang="vue"` recently. Make sure you're on the latest version (`v1.6.4`).

**Comment by louiss0** [comment]
> It's Volar extension that supported `lang="vue"` recently. Make sure you're on the latest version (`v1.6.4`).

I was not able to switch to that version I had to switch to a pre-release version. I don't like to do that. Filing an issue.

Can you tell me the difference between html and vue?

**Comment by hunyan-io** [comment]
> > It's Volar extension that supported `lang="vue"` recently. Make sure you're on the latest version (`v1.6.4`).
> 
> I was not able to switch to that version I had to switch to a pre-release version. I don't like to do that. Filing an issue.
> 
> Can you tell me the difference between html and vue?

There are differences when it comes to syntax highlighting. Try hovering over `<template>`, you'll see that the documentation is different in `html` and `vue`.
