### ISSUE TITLE
Component blocks don't work well now

### ISSUE THREAD

**Issue by louiss0** [HunYan-io/vite-plugin-vue-nested-sfc#8]
Vue version: 3.3.0
Volar version: 1.6.0
Vue Nested SFC Version: 0.1.1

There is another problem with this plugin. Volar seems to not provide typing for the first block and rejects the second one.

I have created two components increment button and message. 

The increment button component does not display and types when you highlight over things. It does not know about define props at all. 
 

**Message component**

![Screenshot 2023-05-11 213315](https://github.com/HunYan-io/vite-plugin-vue-nested-sfc/assets/29028601/8233185e-3fb3-4d1d-b5a3-7ee320deee04)

**Comment by hunyan-io** [comment]
Update Volar to `v1.6.4`

**Comment by louiss0** [comment]
> Update Volar to `v1.6.4`

I was not able to switch to that version I had to switch to a pre-release version. I don't like to do that. Filing an issue.
